### ISSUE TITLE
Mobile: Account/Search/Chromecast button group needs a little bit more spacing on the right side

### ISSUE THREAD

**Issue by AstroEngineeer** [stpnwf/ZestyTheme#13]
**Describe the bug**
The account+chromecast+search button group(top right corner) needs a little bit more spacing on the right side. Also, the scroll bar overlaps it.

**To Reproduce**
1. Open Jellfin in Safari browser
2. Add Jellfin to home
3. Open Jellyfin Safari app
4. Login to Jellyfin

**On a Smartphone or Tablet?**
 - iPhone 15 Pro

**Are you using any extra code in your "Custom CSS" field?**
- No

**Screenshots**
![image](https://github.com/user-attachments/assets/60c56be7-c79e-458b-bdb7-5661c624bb61)

**Comment by stpnwf** [comment]
I just pushed a change to fix this. Lmk if the issue persists.
