### ISSUE TITLE
Icons not visible on my QHD monitor (2560 x 1440)

### ISSUE THREAD

**Issue by xd003** [stpnwf/ZestyTheme#3]
**Describe the bug**
As implied from the title, the icons throughtout jellyfin media player on my QHD monitor appear to be broken. Although the theme appears to be fine when jellyfin web is viewed on the browser
![image](https://github.com/stpnwf/ZestyTheme/assets/26503185/d785d3da-9c74-4eec-8bc5-178cde34cf75)

**On a Smartphone or Tablet?**
 - Device:  Windows 11 QHD monitor

**Are you using any extra code in your "Custom CSS" field?**
If yes, please include it here.
```
@import url('https://cdn.jsdelivr.net/gh/MakD/zombie-release@latest/zombie-min-git.css');
@import url('https://cdn.jsdelivr.net/gh/stpnwf/ZestyTheme@latest/colorschemes/green.css');

/*if the logo is present on the details page and loaded hide the title so it doesnt duplicate and look weird*/
#itemDetailPage .itemName.infoText.parentNameLast > bdi:nth-child(1) {display: none;}
.hide+.detailPageWrapperContainer .itemName > bdi:nth-child(1) {display: block !important;}
/*the same but for the single episodes link back title*/
#itemDetailPage .parentName > bdi:nth-child(1) {display: none;}
.hide+.parentName > bdi:nth-child(1) {display: block !important;}

/* remove My Media title */
.section0 .sectionTitle {display: none;}
```
**Screenshots** (from jellyfin media player)
![image](https://github.com/stpnwf/ZestyTheme/assets/26503185/cd708ce4-5c37-49ee-8df9-9e657647a90b)

![image](https://github.com/stpnwf/ZestyTheme/assets/26503185/543ee063-c927-4a7e-94c8-d8b2aabe75d6)

**Comment by stpnwf** [comment]
Awesome, and glad to hear that it works well on QHD screens. Feel free to create an issue if something looks broken there.
