### ISSUE TITLE
Black Gradient Box in Background in 1440p Desktop

### ISSUE THREAD

**Issue by TimmyTheCool** [stpnwf/ZestyTheme#6]
Hey found this theme today and it looks absolutely beautiful! On desktop, the only issue I see is a black gradient box in the background. See image attached :)

This is my first bug submission thing ever on GitHub so please yell at me if this isn't formatted well enough lol

![Home_Preview](https://github.com/user-attachments/assets/d1935c20-90e6-4d94-a78d-eda06101f191)
![Show_Preview](https://github.com/user-attachments/assets/fd31c12c-caa4-4cec-ac4f-935b903a860d)

**Comment by stpnwf** [comment]
Glad you are enjoying it, and thank you for reporting this.

Can you please try adding this code under your `@import` line and let me know if it works:

```
.layout-desktop .backgroundContainer {background-size: cover;}
```

And if you don't mind, could you send another screenshot of what it looks like if it is successful? The gradients are 1080p and I am wondering how they will look on a 2K screen.

**Comment by TimmyTheCool** [comment]
Hey hey just got around to checking in on this and that code worked and looks good to me! The gradient being stretched to 1440p isn't really noticeable IMO and it's better than it not being stretched so TYSM!
![IMG1](https://github.com/user-attachments/assets/aeb6f868-f4d6-48e9-9558-db80e176fefb)
![IMG2](https://github.com/user-attachments/assets/64628f5e-dd71-485f-8407-9163fe0aec4a)

**Comment by stpnwf** [comment]
Awesome, I will add the fix to the code then. Please keep using that code for the time being, as it takes a while for the changes to be delivered to the import URL.
