### ISSUE TITLE
There is no option to select the 4K or 1080P version before playing. (MergeVersion plugin)

### ISSUE THREAD

**Issue by EinNiki** [stpnwf/ZestyTheme#8]
There is no option to select the 4K or 1080P version before playing. (MergeVersion plugin)

**Comment by Panda260** [comment]
bump

**Comment by stpnwf** [comment]
Thanks for reporting this. I only have one version of movies and thought there would be an option inside the player like there is for audio and subtitles. I will look at this this weekend.

**Comment by stpnwf** [comment]
Had some time today. Does this break anything for you?

https://pastebin.com/zAMdd8gm
